// Requires jsdom. Run from the repository root with node tests/collection-dom.test.cjs.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const {JSDOM,VirtualConsole}=require('jsdom');
const html=fs.readFileSync('index.html','utf8');
const main=html.match(/<script>([\s\S]*?)<\/script>/)[1];
const dom=new JSDOM(html,{url:'https://bulboel.github.io/Slay-TCG/',runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:new VirtualConsole()});
const ctx=dom.getInternalVMContext(),w=dom.window,timers=[];
w.setTimeout=fn=>{timers.push(fn);return timers.length};w.setInterval=()=>0;w.requestAnimationFrame=()=>0;w.confirm=()=>true;
const run=code=>vm.runInContext(code,ctx),plain=code=>JSON.parse(JSON.stringify(run(code)));
for(const file of ['assets/data/card-stats.js','assets/data/september28-cards.js','assets/data/card-numbers.js','collection-polish.js','booster-presentation.js','collection-updates.js','story-mine.js'])run(fs.readFileSync(file,'utf8'));
run(main);run('initCollectionUpdates();initCollectionPolish();initNavigationPolish()');
const $=s=>w.document.querySelector(s);
assert.equal($('#statsCard').options.length,137);
run(`collection.counts=Object.fromEntries(pool.map(c=>[c.id,3]));collection.foils={p03:1};collection.starterBoosters=0;
decks=[{id:'test',name:'Test',cards:['p03','p03','p05','p14','p104'].map(id=>pool.findIndex(c=>c.id===id))}];activeDeckId='test';renderDeckBuilder();`);
assert.match($('#deckCount').textContent,/2 \/ 2 rares/);
run(`newGame('deck')`);
assert.deepEqual(plain('hands.p.map(c=>c.id)'),['p03','p03','p05','p14','p104']);
assert.equal($('#playerHand').querySelectorAll('.is-foil').length,1);
assert.equal(run(`makeCard({...catalogById('p03'),foil:true},'p',0,true).classList.contains('is-foil')`),false);
run(`decks[0].cards=['p05','p14','p28','p33','p03'].map(id=>pool.findIndex(c=>c.id===id));newGame('deck')`);
assert.equal($('#deckScreen').classList.contains('hidden'),false);
assert.match($('#deckCount').textContent,/2 rares et 1 Divine maximum/);
$('#statsCard').value='p42';run('renderStatsCard()');
assert.equal($('[data-stat-side="1"]').value,'6');
$('[data-stat-side="1"]').value='5';$('#statsForm').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
assert.equal(run(`catalogById('p42').v[1]`),5);
assert.deepEqual(JSON.parse(w.localStorage.getItem('hackenia-card-stat-overrides')).p42,[8,5,2,4]);
$('#statsReset').click();assert.equal(run(`catalogById('p42').v[1]`),6);
run(`collection={version:2,counts:{},foils:{},starterBoosters:0};economy.gold=100;buyBoosters(10,90)`);
assert.equal(run('economy.gold'),10);assert.equal(run('collection.shopQueue'),10);
const first=plain('pendingBooster.map(p=>p.card.id)');
run(`collection=JSON.parse(localStorage.getItem('hackenia-collection'));pendingBooster=[];showBooster('chapter')`);
assert.deepEqual(plain('pendingBooster.map(p=>p.card.id)'),first);
assert.equal(run('boosterContext'),'shop');
run(`$('#boosterCards').classList.add('revealed');$('#boosterContinueBtn').disabled=false`);
$('#boosterCards .booster-pull').click();assert.equal($('#cardZoom').classList.contains('hidden'),false);
$('#cardZoomClose').click();run('claimBooster()');
assert.equal(run('pityProgress().opened'),1);assert.equal(run('collection.shopQueue'),9);
run('claimBooster()');assert.equal(run('pityProgress().opened'),1,'Repeated click does not claim the next hidden pack');
run(`pityProgress().opened=24;$('#boosterContinueBtn').disabled=false;claimBooster()`);
assert.equal($('#pityDialog').classList.contains('hidden'),false);
assert.equal(run('pityProgress().pending[0].milestone'),25);
assert.equal($('#pityGrid').querySelectorAll('img,.card,.reward-art').length,0,'Pity choices contain names only');
$('#pityLater').click();assert.equal($('#pityDialog').classList.contains('hidden'),true);
run('continueBoosters()');assert.equal($('#pityDialog').classList.contains('hidden'),false);
$('#pityGrid .reward-option .menu-btn').click();assert.equal(run('pityProgress().pending.length'),0);
assert.equal(run('collection.shopQueue'),8);assert.equal(run('pendingBooster.length'),5);
const profile=plain('progressPayload()');run('loadProfile('+JSON.stringify(profile)+')');
assert.equal(run('pityProgress().opened'),25);assert.equal(run('collection.shopQueue'),8);
assert.equal(run('collection.pendingPack.pulls.length'),5);
run(`pityProgress().opened=50;renderBoosterProgress()`);
assert.match($('#boosterProgress strong').textContent,/0 \/ 50/);
run(`collection={version:2,counts:{},foils:{},starterBoosters:0};story=defaultStory();economy=defaultEconomy();finishStoryPart1()`);
assert.equal(run('collection.pendingPack.context'),'chapter');
assert.deepEqual(plain('collection.storyBoosterQueue'),['part1']);
run(`$('#boosterContinueBtn').disabled=false;claimBooster();finishForestPart()`);
assert.deepEqual(plain('collection.storyBoosterQueue'),['part2']);
run(`$('#boosterContinueBtn').disabled=false;claimBooster();finishCabinPart()`);
assert.deepEqual(plain('collection.storyBoosterQueue'),['part3']);
run(`$('#boosterContinueBtn').disabled=false;claimBooster();finishStoryPart1();finishForestPart();finishCabinPart()`);
assert.deepEqual(plain('collection.storyBoosterQueue'),[],'Replay does not duplicate rewards');
run(`story={...defaultStory(),part1:'complete',part2:'complete',part3:'complete',pendingReward:true};economy.storyRewards={part1:true,part2:true,part3:true};collection.storyBoosterQueue=[];recoverStoryBoosters();recoverStoryBoosters()`);
assert.deepEqual(plain('collection.storyBoosterQueue'),['part3','part1','part2'],'Legacy pending reward and missing rewards are all retained exactly once');
run('showForestVictory()');
assert.match(run('storySequence.at(-1).text'),/fumée/);
assert.equal(run('storySequence.at(-1).finalLabel'),'Terminer la partie 2');
// Part 4: migration from a completed part 3, resumable duel, victory gate and one reward.
run(`collection={version:2,counts:{},foils:{},starterBoosters:0};story={...defaultStory(),part1:'complete',part2:'complete',part3:'complete',boosterRewards:{part1:true,part2:true,part3:true}};economy=defaultEconomy();decks=defaultDecks();activeDeckId=decks[0].id;renderStoryMenu();startMinePart()`);
assert.equal($('#chapter1Part4Btn').disabled,false);
assert.equal(run('storySequence.length'),5);
assert.match(run('storySequence[0].text'),/Grimgors et Jhimm/);
run('nextStoryBeat();nextStoryBeat()');
assert.equal(run('story.mineStep'),2);
run('startMinePart()');assert.equal(run('storyStep'),2,'Dialogue resumes');
run('startMineGame()');assert.equal(run('currentMode'),'story-mine');
assert.equal(run('hands.p.length'),5);assert.equal(run('hands.a.length'),5);
run(`board[0]={card:hands.p.shift(),owner:'p'};saveStoryMatch();board=[];startMinePart()`);
assert.equal(run('board[0].owner'),'p','Duel resumes from story menu');
assert.equal($('#rightLabel').textContent,'La voix de la torche');
run('endMineGame({p:3,a:6});finishMinePart()');
assert.equal(run('story.part4'),'retry');assert.equal(run('collection.storyBoosterQueue?.length||0'),0);
run('startMinePart();endMineGame({p:5,a:4});showMineVictory()');
assert.equal(run('storySequence.length'),5);
assert.match(run('storySequence[3].text'),/araignée blanche/);
run('nextStoryBeat();startMinePart()');assert.equal(run('storyStep'),1,'Victory epilogue resumes');
run('finishMinePart()');assert.equal(run('story.part4'),'complete');assert.equal(run('economy.gold'),50);
assert.deepEqual(plain('collection.storyBoosterQueue'),['part4']);
run(`$('#boosterContinueBtn').disabled=false;claimBooster();finishMinePart()`);
assert.equal(run('economy.gold'),50);assert.deepEqual(plain('collection.storyBoosterQueue'),[]);
run(`collection.counts={p27:10,p26:9,p107:100,p04:10,p08:10,p13:10};collection.foils={p27:1};decks=defaultDecks();activeDeckId=decks[0].id;renderCollection();renderDeckBuilder()`);
assert($('#collectionGrid [data-card-id="p27"] .mastery-frame.gold'));
assert.equal($('#collectionGrid [data-card-id="p26"] .mastery-frame'),null,'Variants do not share mastery counts');
assert($('#collectionGrid [data-card-id="p107"] .mastery-frame.diamond'));
const originalIds=plain('pool.map(c=>c.id)');
$('#deckSort').value='name';$('#deckSort').dispatchEvent(new w.Event('change'));
$('#deckGrid [data-card-id="p27"] .deck-plus').click();
assert.equal(run('pool[activeDeck().cards[0]].id'),'p27','Sorted deck selection uses stable pool indices');
assert.deepEqual(plain('pool.map(c=>c.id)'),originalIds);
run(`decks[0].cards=['p27','p107','p04','p08','p13'].map(id=>pool.findIndex(c=>c.id===id));newGame('deck')`);
assert.equal($('#playerHand').querySelectorAll('.mastery-frame.gold').length,4);
assert.equal($('#playerHand').querySelectorAll('.mastery-frame.diamond').length,1);
assert.equal(run(`makeCard({...playerCard(catalogById('p107')),foil:true},'p',0,true).querySelector('.mastery-frame')`),null,'Hidden cards reveal no frame');
const beforeTutorial=plain('progressPayload()');
run('openTutorial();tutorialStep=2;renderTutorial()');
assert.equal($('#tutorialNext').disabled,true);
$('#tutorialPractice .tutorial-hand').click();$('#tutorialPractice .tutorial-cell:nth-child(4)').click();
assert.equal($('#tutorialNext').disabled,false);assert.equal($('#tutorialPractice .captured').textContent,'Ma carte · droite : 6');
run('closeTutorial()');assert.deepEqual(plain('progressPayload()'),beforeTutorial,'Tutorial does not mutate progress or deck');
dom.window.close();
console.log('PASS: full page boot, stats editor, deck launch, foil, booster zoom, ten-pack persistence, double-click guard, pity choice and save import.');
run(`collection.counts.p03=10;collection.foils.p03=1;renderDeckBuilder()`);
const deckVisual=$('#deckGrid [data-card-id="p03"] .card');
const cardsBefore=plain('activeDeck().cards');
deckVisual.click();
assert.equal($('#cardZoom').classList.contains('hidden'),false);
assert.equal($('#cardZoomName').textContent,run("catalogById('p03').name"));
assert.deepEqual(plain('activeDeck().cards'),cardsBefore,'Zoom does not add or remove a card');
assert.equal($('#cardZoomVisual .card').classList.contains('is-foil'),true);
run(`closeCardZoom()`);
deckVisual.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));
assert.equal($('#cardZoom').classList.contains('hidden'),false);
assert.equal($('#deckGrid .locked .card')?.hasAttribute('role'),false,'Undiscovered cards stay hidden');
console.log('PASS: deck card zoom by click and keyboard preserves the deck and shows foil.');

assert.equal(run(`memoryById('dreamers')`),undefined);
for(let i=0;i<20;i++)assert.equal(run(`freshMemoryDeck().includes('dreamers')`),false);
run(`restoreStoryMatch({mode:'story-mine',board:Array(9).fill(null),hands:{p:[],a:[]},turn:'p',memoryDeck:['rest','dreamers','rock']})`);
assert.deepEqual(plain('memoryDeck'),['rest','rock']);
for(const id of ['collectionSort','deckSort']){
 assert([...$('#'+id).options].some(o=>o.value==='name-desc'));
 assert([...$('#'+id).options].some(o=>o.value==='rarity-desc'));
 $('#'+id).value='rarity-desc';$('#'+id).dispatchEvent(new w.Event('change'));
 assert.equal(JSON.parse(w.localStorage.getItem('hackenia-'+id)),'rarity-desc');
}
console.log('PASS: removed Souvenir, legacy story pile migration and persisted inverse sorts.');

run(`story={...defaultStory(),part4:'complete'};collection.storyBoosterQueue=[];story.pendingReward=false;economy={gold:0,storyRewards:{}};decks=defaultDecks();activeDeckId=decks[0].id;renderStoryMenu()`);
assert.equal($('#chapter1Part5Btn').disabled,false);
run(`startFinalMinePart();nextStoryBeat();startFinalMinePart()`);assert.equal(run('storyStep'),1);
run(`startFinalMineGame();board[0]={card:hands.p.shift(),owner:'p'};saveStoryMatch();board=[];startFinalMinePart()`);assert.equal(run('board[0].owner'),'p');
assert.equal($('#rightLabel').textContent,'L’araignée géante');
run(`endFinalMineGame({p:4,a:5});finishFinalMinePart()`);assert.equal(run('story.part5'),'retry');assert.equal(run('economy.gold'),0);
run(`startFinalMineGame();endFinalMineGame({p:5,a:4});showFinalMineVictory();nextStoryBeat();startFinalMinePart()`);assert.equal(run('storyStep'),1);
assert.match(run('storySequence[0].text'),/gourdin/);assert.match(run('storySequence[3].text'),/portail/);
run(`finishFinalMinePart();finishFinalMinePart()`);assert.equal(run('economy.gold'),50);assert.deepEqual(plain('collection.storyBoosterQueue'),['part5']);assert.equal(run('story.part5'),'complete');
run(`$('#turnCover').classList.add('hidden');passing=false;hands={p:[playerCard(catalogById('p140')),playerCard(catalogById('p27'))],a:[]};blindHands={p:false,a:false};turn='p';locked=false;gameType='ai';render();inspectHand('p')`);
assert.equal($('#cardZoomName').textContent,'Le pèlerin');assert.equal($('#handZoomPosition').textContent,'1 / 2');$('#handZoomNext').click();assert.equal($('#cardZoomName').textContent,'Kala');
run(`closeCardZoom();blindHands.p=true;render();inspectHand('p')`);assert.equal($('#cardZoom').classList.contains('hidden'),true,'Loupe cannot reveal a blinded hand');
assert($('#collectionScreen .catalog-backbar'));assert($('#deckScreen .catalog-backbar'));
console.log('PASS: part 5 victory gate, resume, one-time rewards, hand zoom privacy and navigation.');

run(`collection.pendingPack=null;collection.boosterProgress={};collection.starterBoosters=0;showBooster('shop');window.angelDone=0;animateBoosterAngel({card:catalogById('p148')},()=>window.angelDone++)`);
assert($('.booster-angel-stage'));assert($('#boosterCards .booster-pull:last-child').classList.contains('angel-pending'));
$('.angel-skip').click();assert.equal(w.angelDone,1);assert.equal($('.booster-angel-stage'),null);
run(`animateBoosterAngel({card:catalogById('p29')},()=>window.angelDone++)`);assert.equal(w.angelDone,2);assert.equal($('.booster-angel-stage'),null);
w.matchMedia=()=>({matches:true});run(`animateBoosterAngel({card:catalogById('p107')},()=>window.angelDone++)`);assert.equal(w.angelDone,3);assert.equal($('.booster-angel-stage'),null);
w.matchMedia=()=>({matches:false});run(`animateBoosterAngel({card:catalogById('p30')},()=>window.angelDone++);cancelBoosterAngel()`);assert.equal(w.angelDone,3);assert.equal($('.booster-angel-stage'),null);
console.log('PASS: angel reveal rarity gate, skip, cancellation and reduced motion.');

// Booster presentation never changes or claims the saved pack on its own.
timers.length=0;w.matchMedia=()=>({matches:true});
run(`collection.boosterProgress={};collection.pendingPack={context:'shop',pulls:['p04','p27','p147','p29','p150'].map((id,i)=>({id,foil:i===4,slot:'Test'}))};showBooster('shop');beginBoosterPresentation()`);
const savedPack=plain('collection.pendingPack');
const flush=()=>{let guard=0;while(timers.length){assert(++guard<100,'Finite presentation timers');timers.shift()()}};
flush();assert.equal(run('boosterPresentation.seen'),0);assert.equal($('#boosterContinueBtn').disabled,true);
assert.equal($('#boosterCards .active').getAttribute('aria-hidden'),'false');
$('#boosterNextBtn').click();flush();assert.equal(run('boosterPresentation.seen'),1);
$('#boosterSkipAll').click();flush();assert.equal(run('boosterPresentation.seen'),4);assert.equal($('#boosterContinueBtn').disabled,false);
assert.deepEqual(plain('collection.pendingPack'),savedPack,'Presentation does not reroll or claim cards');
$('#boosterStepDots button').click();assert.equal(run('boosterPresentation.index'),0);assert.equal($('#boosterContinueBtn').disabled,false);
run('showBooster("shop");openBoosterPack();showBooster("shop")');flush();assert.equal(run('boosterPresentation.seen'),-1,'Stale opening timers cannot reveal a replacement screen');
assert.equal($('#boosterContinueBtn').disabled,true);
assert(fs.statSync(run("catalogById('p150').image.src")).size>10000,'Card 94 has a nonempty illustration');
console.log('PASS: sequential reveal, skip, revisit, claim gate, stable pack and cancelled opening timers.');

// Export refreshes the local load slot as well as the downloaded file.
let exportedText='';const NativeBlob=w.Blob;w.Blob=class{constructor(parts){exportedText=parts.join('')}};
w.URL.createObjectURL=()=> 'blob:test-save';w.URL.revokeObjectURL=()=>{};
run(`saveSlotActive=false;economy={gold:41,storyRewards:{}};writeSaveSlot(null);saveSlotActive=false;economy.gold=987;matchInProgress=false;exportProgress()`);
assert.equal(JSON.parse(exportedText).profile.economy.gold,987);
assert.equal(JSON.parse(w.localStorage.getItem('hackenia-save-slot')).profile.economy.gold,987);
assert.equal(JSON.parse(w.localStorage.getItem('hackenia-economy')).gold,987);
run('economy.gold=0;restoreSavedGame()');assert.equal(run('economy.gold'),987);
run('economy.gold=0;exportProgress()');assert.equal(JSON.parse(exportedText).profile.economy.gold,0,'Zero coins must stay zero');
w.Blob=NativeBlob;
run(`dragState=null;locked=false;turn='p';startDrag({pointerType:'touch',button:0},'p',0,$('#playerHand .card'))`);assert.equal(run('dragState'),null,'Touch scrolling does not start a drag');
console.log('PASS: export and local load slot retain exact current gold, including zero; touch does not start a drag.');
