// Requires jsdom. Run from the repository root with node tests/collection-dom.test.cjs.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const {JSDOM,VirtualConsole}=require('jsdom');
const html=fs.readFileSync('index.html','utf8');
const main=html.match(/<script>([\s\S]*?)<\/script>/)[1];
const dom=new JSDOM(html,{url:'https://bulboel.github.io/Slay-TCG/',runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:new VirtualConsole()});
const ctx=dom.getInternalVMContext(),w=dom.window,timers=[];
w.setTimeout=fn=>{timers.push(fn);return timers.length};w.setInterval=()=>0;w.requestAnimationFrame=()=>0;w.confirm=()=>true;
const run=code=>vm.runInContext(code,ctx),plain=code=>JSON.parse(JSON.stringify(run(code)));
for(const file of ['assets/data/card-stats.js','collection-updates.js'])run(fs.readFileSync(file,'utf8'));
run(main);run('initCollectionUpdates()');
const $=s=>w.document.querySelector(s);
assert.equal($('#statsCard').options.length,83);
run(`collection.counts=Object.fromEntries(pool.map(c=>[c.id,3]));collection.foils={p03:1};collection.starterBoosters=0;
decks=[{id:'test',name:'Test',cards:['p03','p03','p05','p14','p28'].map(id=>pool.findIndex(c=>c.id===id))}];activeDeckId='test';renderDeckBuilder();`);
assert.match($('#deckCount').textContent,/3 \/ 3 rares/);
run(`newGame('deck')`);
assert.deepEqual(plain('hands.p.map(c=>c.id)'),['p03','p03','p05','p14','p28']);
assert.equal($('#playerHand').querySelectorAll('.is-foil').length,1);
assert.equal(run(`makeCard({...catalogById('p03'),foil:true},'p',0,true).classList.contains('is-foil')`),false);
run(`decks[0].cards=['p05','p14','p28','p33','p03'].map(id=>pool.findIndex(c=>c.id===id));newGame('deck')`);
assert.equal($('#deckScreen').classList.contains('hidden'),false);
assert.match($('#deckCount').textContent,/3 rares maximum/);
$('#statsCard').value='p42';run('renderStatsCard()');
assert.equal($('[data-stat-side="1"]').value,'6');
$('[data-stat-side="1"]').value='5';$('#statsForm').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
assert.equal(run(`catalogById('p42').v[1]`),5);
assert.deepEqual(JSON.parse(w.localStorage.getItem('hackenia-card-stat-overrides')).p42,[8,5,2,4]);
$('#statsReset').click();assert.equal(run(`catalogById('p42').v[1]`),6);
run(`collection={version:2,counts:{},foils:{},starterBoosters:0};economy.gold=100;buyBoosters(10,90)`);
assert.equal(run('economy.gold'),10);assert.equal(run('collection.shopQueue'),10);
const first=plain('pendingBooster.map(p=>p.card.id)');
run(`collection=JSON.parse(localStorage.getItem('hackenia-collection'));pendingBooster=[];showBooster('chapter')`);
assert.deepEqual(plain('pendingBooster.map(p=>p.card.id)'),first);
assert.equal(run('boosterContext'),'shop');
run(`$('#boosterCards').classList.add('revealed');$('#boosterContinueBtn').disabled=false`);
$('#boosterCards .booster-pull').click();assert.equal($('#cardZoom').classList.contains('hidden'),false);
$('#cardZoomClose').click();run('claimBooster()');
assert.equal(run('pityProgress().opened'),1);assert.equal(run('collection.shopQueue'),9);
run('claimBooster()');assert.equal(run('pityProgress().opened'),1,'Repeated click does not claim the next hidden pack');
run(`pityProgress().opened=24;$('#boosterContinueBtn').disabled=false;claimBooster()`);
assert.equal($('#pityDialog').classList.contains('hidden'),false);
assert.equal(run('pityProgress().pending[0].milestone'),25);
assert.equal($('#pityGrid').querySelectorAll('img,.card,.reward-art').length,0,'Pity choices contain names only');
$('#pityLater').click();assert.equal($('#pityDialog').classList.contains('hidden'),true);
run('continueBoosters()');assert.equal($('#pityDialog').classList.contains('hidden'),false);
$('#pityGrid .reward-option .menu-btn').click();assert.equal(run('pityProgress().pending.length'),0);
assert.equal(run('collection.shopQueue'),8);assert.equal(run('pendingBooster.length'),5);
const profile=plain('progressPayload()');run('loadProfile('+JSON.stringify(profile)+')');
assert.equal(run('pityProgress().opened'),25);assert.equal(run('collection.shopQueue'),8);
assert.equal(run('collection.pendingPack.pulls.length'),5);
run(`pityProgress().opened=50;renderBoosterProgress()`);
assert.match($('#boosterProgress strong').textContent,/0 \/ 50/);
run(`collection={version:2,counts:{},foils:{},starterBoosters:0};story=defaultStory();economy=defaultEconomy();finishStoryPart1()`);
assert.equal(run('collection.pendingPack.context'),'chapter');
assert.deepEqual(plain('collection.storyBoosterQueue'),['part1']);
run(`$('#boosterContinueBtn').disabled=false;claimBooster();finishForestPart()`);
assert.deepEqual(plain('collection.storyBoosterQueue'),['part2']);
run(`$('#boosterContinueBtn').disabled=false;claimBooster();finishCabinPart()`);
assert.deepEqual(plain('collection.storyBoosterQueue'),['part3']);
run(`$('#boosterContinueBtn').disabled=false;claimBooster();finishStoryPart1();finishForestPart();finishCabinPart()`);
assert.deepEqual(plain('collection.storyBoosterQueue'),[],'Replay does not duplicate rewards');
run(`story={...defaultStory(),part1:'complete',part2:'complete',part3:'complete',pendingReward:true};economy.storyRewards={part1:true,part2:true,part3:true};collection.storyBoosterQueue=[];recoverStoryBoosters();recoverStoryBoosters()`);
assert.deepEqual(plain('collection.storyBoosterQueue'),['part3','part1','part2'],'Legacy pending reward and missing rewards are all retained exactly once');
run('showForestVictory()');
assert.match(run('storySequence.at(-1).text'),/fumée/);
assert.equal(run('storySequence.at(-1).finalLabel'),'Terminer la partie 2');
dom.window.close();
console.log('PASS: full page boot, stats editor, deck launch, foil, booster zoom, ten-pack persistence, double-click guard, pity choice and save import.');
