// Run from repository root. Requires playwright; optional CHROMIUM_EXECUTABLE_PATH.
const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert');
const {chromium}=require('playwright');
(async()=>{
 const server=http.createServer((q,r)=>{let f=path.join(process.cwd(),decodeURIComponent(q.url.split('?')[0]));if(f.endsWith('/'))f+='index.html';r.setHeader('Content-Type',({'html':'text/html','js':'text/javascript','css':'text/css','webp':'image/webp','png':'image/png'})[f.split('.').pop()]||'application/octet-stream');fs.createReadStream(f).on('error',()=>{r.statusCode=404;r.end()}).pipe(r)});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const opts={headless:true};if(process.env.CHROMIUM_EXECUTABLE_PATH){opts.executablePath=process.env.CHROMIUM_EXECUTABLE_PATH;opts.args=require('@sparticuz/chromium').default.args}
 const browser=await chromium.launch(opts);
 try{
 const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:'+server.address().port);await page.screenshot({path:'/tmp/polish-startup.png'});
 const title=await page.locator('#startupScreen .menu-title').boundingBox(),box=await page.locator('#startupScreen .menu-card').boundingBox();assert(Math.abs(title.x+title.width/2-box.x-box.width/2)<1,'Title centred');assert(title.width<=box.width);
 await page.evaluate(()=>{$('#startupScreen').classList.add('hidden');collection.counts=Object.fromEntries(catalog.map(c=>[c.id,100]));renderCollection();showMenu()});
 for(const name of ['collection','deck','shop','story','options','pvp','mode']){
  await page.evaluate(name=>{if(name==='deck')renderDeckBuilder();openPanel('#'+name+'Screen')},name);await page.screenshot({path:'/tmp/polish-'+name+'.png'});
  assert(await page.locator('#'+name+'Screen').evaluate(e=>e.scrollWidth<=e.clientWidth+1),'Panel overflow '+name);
 }
 await page.evaluate(()=>openPanel('#optionsScreen'));assert(await page.locator('[data-effect="spider"] .memory-skin-choice').count());await page.locator('#testAudioBtn').tap();await page.waitForFunction(()=>AudioEngine.state.contextState==='running');await page.evaluate(()=>AudioEngine.suspend());await page.waitForFunction(()=>AudioEngine.state.contextState==='suspended');await page.locator('#testAudioBtn').tap();await page.waitForFunction(()=>AudioEngine.state.contextState==='running');
 if(process.env.HACKENIA_SHOWCASE_SAVE){
  await page.locator('#importSaveFile').setInputFiles(process.env.HACKENIA_SHOWCASE_SAVE);await page.waitForFunction(()=>economy.unlimitedGold===true);
  assert.equal(await page.locator('#optionsScreen').evaluate(()=>document.querySelector('.gold-value').textContent),'∞');
  await page.evaluate(()=>buyBoosters(10,90));assert.equal(await page.evaluate(()=>collection.shopQueue),10);assert.equal(await page.evaluate(()=>economy.gold),0);
  assert(await page.evaluate(()=>JSON.parse(localStorage.getItem(SAVE_KEY)).profile.economy.unlimitedGold));
  await page.evaluate(()=>{resetBoosterPresentation();cancelBoosterAngel();$('#boosterReveal').classList.add('hidden');collection.pendingPack=null;collection.shopQueue=0});
 }
 const seed=async()=>page.evaluate(()=>{document.querySelectorAll('.panel-screen').forEach(e=>e.classList.add('hidden'));$('#menuScreen').classList.add('hidden');$('#gameApp').classList.remove('hidden');gameType='local';$('#splitScreen').checked=true;$('#passScreen').checked=false;currentMode='pvp';turn='p';locked=false;passing=false;memoryPending=false;blindHands={p:false,a:false};hands={p:['p27','p04','p08','p13','p29'].map(id=>playerCard(catalogById(id))),a:['p27','p04','p08','p13','p29'].map(id=>playerCard(catalogById(id)))};board=Array(9).fill(null);playedOrder=[];resetMemories();render()});
 await seed();await page.waitForTimeout(300);const cdp=await page.context().newCDPSession(page);
 const touch=async(type,x,y)=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints:type==='touchEnd'||type==='touchCancel'?[]:[{x,y}]});
 let r=await page.locator('#playerHand .card').first().boundingBox(),x=r.x+r.width/2,y=r.y+r.height/2;
 await touch('touchStart',x,y);await page.waitForFunction(()=>!document.querySelector('#cardZoom').classList.contains('hidden'));assert(await page.locator('#cardZoom').isVisible(),'Holding zooms hand');assert(await page.locator('#cardZoom .mastery-halo.diamond').count());assert.equal(await page.evaluate(()=>board.filter(Boolean).length),0);await touch('touchEnd');assert(await page.locator('#cardZoom').isHidden(),'Release closes hand preview');
 await page.waitForTimeout(850);r=await page.locator('#playerHand .card').first().boundingBox();x=r.x+r.width/2;y=r.y+r.height/2;const target=await page.locator('.cell').nth(4).boundingBox(),tx=target.x+target.width/2,ty=target.y+target.height/2;
 await touch('touchStart',x,y);for(let i=1;i<=8;i++)await touch('touchMove',x+(tx-x)*i/8,y+(ty-y)*i/8);await touch('touchEnd');await page.waitForFunction(()=>board[4]?.card.id==='p27');assert(await page.locator('#cardZoom').isHidden(),'Dragging does not zoom');
 assert(await page.locator('#board .catalog-number').isHidden());assert(await page.locator('#board .mastery-halo').isHidden());
 await page.waitForTimeout(450);r=await page.locator('#board .card').boundingBox();await touch('touchStart',r.x+r.width/2,r.y+r.height/2);await page.waitForFunction(()=>!document.querySelector('#cardZoom').classList.contains('hidden'));assert(await page.locator('#cardZoom').isVisible(),'Holding board zooms');assert(await page.locator('#cardZoom .mastery-halo.diamond').isVisible());await touch('touchEnd');assert(await page.locator('#cardZoom').isHidden(),'Release closes board preview');
 await seed();await page.evaluate(()=>{board[4]={card:playerCard(catalogById('p27')),owner:'p'};render()});for(const [width,height] of [[390,844],[390,667],[320,568],[844,390]]){await page.setViewportSize({width,height});await page.screenshot({path:`/tmp/polish-duel-${width}-${height}.png`});const b=await page.locator('#board').boundingBox();assert(b.x>=0&&b.y>=0&&b.x+b.width<=width+1&&b.y+b.height<=height+1,'Board fits');const hand=await page.locator('#playerHand').boundingBox();assert(hand.y+hand.height<=height+1,'Hand fits');const cards=await page.locator('#playerHand .card').evaluateAll(es=>es.map(e=>e.getBoundingClientRect().toJSON()));assert(cards.every(c=>c.x>=0&&c.right<=width+1),'Five cards fit horizontally');if(width<height){const placed=await page.locator('#board .card').boundingBox();assert(cards[0].height>=placed.height*.85,'Hand cards as readable as board')}}
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{collection.pendingPack={context:'shop',pulls:['p04','p27','p147','p29','p56'].map((id,i)=>({id,foil:i===4,slot:'Test'}))};collection.boosterProgress={};showBooster('shop');openBoosterPack()});const began=Date.now();await page.waitForFunction(()=>boosterPresentation.index===3&&document.querySelector('.rare-spark-burst'));assert.equal(await page.locator('.rare-spark-burst i').count(),24);await page.waitForFunction(()=>boosterPresentation.index===4&&document.querySelector('.booster-pull.active .rare-spark-burst'));assert.equal(await page.locator('.booster-pull.active .rare-spark-burst i').count(),24);await page.waitForFunction(()=>boosterPresentation.seen===4&&!boosterPresentation.busy);assert(Date.now()-began<11000,'Opening is faster');await page.waitForSelector('.rare-spark-burst',{state:'detached'});
 assert.deepEqual(errors,[]);console.log('PASS: themed menus, sound resume, spider option, touch drag, hold/release hand and board previews, touch drag, large five-card hand, infinite-gold import and rare sparks in slots 4 and 5.');
 }finally{await browser.close();server.close()}
})().catch(e=>{console.error(e);process.exit(1)});
