const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const nodes=new Map();const $=key=>{if(!nodes.has(key))nodes.set(key,{textContent:'',disabled:false,style:{},classList:{toggle(){},add(){},remove(){}}});return nodes.get(key)};
const c={console,$,story:{part4:'complete',part5:'complete',stage:'part5-complete'},economy:{gold:0,storyRewards:{}},collection:{},readSaved:()=>null,saveStory(){},saveCollection(){},saveStoryMatch(){},applyRulePreset(){},activeDeck:()=>({cards:[]}),validDeck:()=>false,catalogById:id=>({id}),playerCard:x=>({...x}),cloneCard:x=>({...x}),resetMemories(){},render(){},msg(){},showStoryMenu(){},document:{querySelectorAll:()=>[]},localStorage:{removeItem(){}},setTimeout:fn=>fn(),awardGold:n=>c.economy.gold+=n,queueStoryBooster:part=>{c.collection[part]??=1},runStorySequence:(sequence,after,start=0)=>{c.sequence=sequence;c.after=after;c.step=start},restoreStoryMatch:saved=>c.restored=saved};
vm.createContext(c);vm.runInContext(fs.readFileSync('story-mine.js','utf8'),c);
c.startFinalMinePart();assert(c.sequence.some(b=>b.speaker==='Kala'&&b.text.includes('inoffensives')));assert(c.sequence.some(b=>b.speaker==='Jhimm'));assert(c.sequence.some(b=>b.text.includes('retourne retrouver ses amis')));assert(c.sequence.some(b=>b.cast.includes('spider')));assert(c.sequence.some(b=>b.cast.includes('grimgors')));
c.startFinalMineGame();assert.deepEqual(Array.from(c.hands.a,x=>x.id),Array(5).fill('p02'));assert.equal(new Set(c.hands.a).size,5,'Spider cards are independent copies');
c.story.part5='complete';c.story.stage='part5-complete';c.startRescuePart();assert.equal(c.sequence.length,6);assert(c.sequence.some(b=>b.cast.includes('wolves')));for(const key of ['kala','jhimm','grimgors','bolduc','eberien'])assert(c.sequence.some(b=>b.cast.includes(key)),key+' appears in the group');assert(c.sequence.some(b=>b.speaker==='Jhimm'));c.story.rescueStep=3;c.startRescuePart();assert.equal(c.step,3);c.after();assert.equal(c.currentMode,'story-wolves');assert.deepEqual(Array.from(c.hands.a,x=>x.id),Array(5).fill('p16'));assert.equal(new Set(c.hands.a).size,5);
for(const counts of [{p:3,a:6},{p:4,a:4}]){c.endRescueGame(counts);assert.equal(c.story.part6,'retry');assert.equal(c.story.rescueWon,false);c.finishRescuePart();assert.equal(c.economy.gold,0);c.after();}
c.endRescueGame({p:5,a:4});assert.equal(c.story.stage,'part6-victory');const invitation=c.sequence.find(b=>b.speaker==='Ébérien'&&b.text.startsWith('Venez avec nous'));assert(invitation);assert.equal(invitation.emotions.jhimm,'neutral');assert.equal(c.sequence.filter(b=>b.mood==='happy').length,1,'Only the laughter scene has a joyful group');assert(c.sequence.some(b=>b.mood==='happy'&&b.text.includes('explosent de rire')));assert(c.sequence.some(b=>b.flashback&&b.cast.includes('violette')&&b.cast.includes('mirahel')&&b.cast.includes('lama')));assert(c.sequence.some(b=>b.flashback&&b.text.includes('explosent de rire')));assert.equal(c.sequence.at(-1).flashback,undefined);c.story.rescueStep=5;c.showRescueVictory();assert.equal(c.step,5);c.after();assert.equal(c.story.part6,'complete');assert.equal(c.story.chapter1,'started');assert.equal(c.economy.gold,50);c.finishRescuePart();assert.equal(c.economy.gold,50);
c.story.stage='part6-match';c.readSaved=()=>({mode:'story-wolves',hands:{a:[{id:'p16'}]}});c.startRescuePart();assert.equal(c.restored.mode,'story-wolves');
console.log('PASS: Jhimm evacuation, wolf-only hand, resume, defeat/draw guards, monochrome flashback, completion and one-time gold.');

c.story.part6='complete';c.story.part6bis='complete';c.story.stage='part6-complete';c.readSaved=()=>null;c.startCavePart();assert.equal(c.sequence.length,14);assert(c.sequence.some(b=>b.speaker==='Messire Balai'&&b.text.includes('atours')));assert(c.sequence.some(b=>b.emotions?.bolduc==='happy'&&b.emotions.jhimm==='embarrassed'));assert(c.sequence.some(b=>b.cast.length===0&&b.text.includes('nus')));c.story.caveStep=7;c.startCavePart();assert.equal(c.step,7);c.after();assert.equal(c.currentMode,'story-ghosts');assert.deepEqual(Array.from(c.hands.a,x=>x.id),Array(5).fill('p37'));assert.equal(new Set(c.hands.a).size,5);
for(const counts of [{p:3,a:6},{p:4,a:4}]){c.endCaveGame(counts);assert.equal(c.story.part7,'retry');c.finishCavePart();assert.equal(c.economy.gold,50);c.after();}
c.endCaveGame({p:5,a:4});assert(c.sequence.at(-1).portal);c.story.caveStep=1;c.showCaveVictory();assert.equal(c.step,1);c.after();assert.equal(c.story.part7,'complete');assert.equal(c.story.chapter1,'complete');assert.equal(c.economy.gold,100);c.finishCavePart();assert.equal(c.economy.gold,100);c.story.stage='part7-match';c.readSaved=()=>({mode:'story-ghosts'});c.startCavePart();assert.equal(c.restored.mode,'story-ghosts');console.log('PASS: cave narrative, ghost-only deck, retry, resume and one-time rewards');

c.story.part6bis='new';c.story.part7='new';c.story.stage='part6-complete';c.readSaved=()=>null;assert.equal(c.caveAccessible(),false);c.startNewFacesPart();assert.equal(c.sequence.length,15);assert(c.sequence.some(b=>b.speaker==='Ven'&&b.text.includes('plus important')));assert(c.sequence.some(b=>b.mood==='blasé'));assert.equal(c.sequence.filter(b=>b.speaker==='Frolgor').length,0);c.story.newFacesStep=8;c.startNewFacesPart();assert.equal(c.step,8);c.after();assert.equal(c.currentMode,'story-ven');assert.deepEqual(Array.from(c.hands.a,x=>x.id),['p42','p10','story-pennedra','p10','story-pennedra']);assert.equal(new Set(c.hands.a).size,5);assert.deepEqual(Array.from(c.hands.a[2].v),[3,3,7,7]);for(const counts of [{p:3,a:6},{p:4,a:4}]){c.endNewFacesGame(counts);assert.equal(c.story.part6bis,'retry');c.finishNewFacesPart();assert.equal(c.economy.gold,100);c.after();}c.endNewFacesGame({p:5,a:4});c.story.newFacesStep=1;c.showNewFacesVictory();assert.equal(c.step,1);c.after();assert.equal(c.story.part6bis,'complete');assert(c.caveAccessible());assert.equal(c.economy.gold,150);c.finishNewFacesPart();assert.equal(c.economy.gold,150);c.story.stage='part6bis-match';c.readSaved=()=>({mode:'story-ven'});c.startNewFacesPart();assert.equal(c.restored.mode,'story-ven');c.story.part6bis='new';c.story.part7='complete';assert(c.caveAccessible());console.log('PASS: new faces order, narrative, silent Frolgor, rival-only hand, resume, retries, one-time rewards and legacy progress');
